feat: add in multi layer env

diff --git a/base/bin/aws-s3-deploy b/base/bin/aws-s3-deploy
--- a/base/bin/aws-s3-deploy
+++ b/base/bin/aws-s3-deploy
@@ -3,19 +3,17 @@ set -e
 # Example Use:
 # $ AWS_REGION=ca-central-1 AWS_PROFILE=****** AWS_CLOUDFRONT_ID=******* ./bin/aws-s3-deploy s3-bucket-name ./build /
 
-# ENV
-. ./env.gitflow
-if [ -e "./env.${ENVIRONMENT}" ]; then
-  . ./env.${ENVIRONMENT}
-fi
-
 # Ensure required vars a set
-if [[ ( -z "${AWS_PROFILE}") && ( -z "${AWS_ACCESS_KEY_ID}" || -z "${AWS_SECRET_ACCESS_KEY}") ]]; then
-    echo "AWS credentials are not set. ex 'AWS_PROFILE=default aws-s2-deploy \${source_dir} \${bucket_name}'"
+if [ -z "${AWS_DEFAULT_PROFILE}" ]; then
+    echo "AWS credentials are not set. ex 'AWS_DEFAULT_PROFILE=default aws-s3-deploy \${source_dir} \${bucket_name}'"
     exit 1;
 fi
-if [ -z "${AWS_REGION}" ]; then echo "AWS_REGION not set. 'AWS_REGION=ca-central-1 aws-s2-deploy \${source_dir} \${bucket_name}'"; exit 1; fi
-if [ -z "${1}" ]; then echo "Destination bucket name required. 'aws-s2-deploy \${source_dir} \${bucket_name}'"; exit 1; fi
+if [ -z "${1}" ]; then
+  echo "Destination bucket name required. 'aws-s3-deploy \${source_dir} \${bucket_name}'";
+  exit 1;
+fi
+
+AWS_REGION=${AWS_REGION:-${AWS_DEFAULT_REGION}}
 
 BUCKET_NAME=$1
 SOURCE_DIR=${2:-./}
@@ -45,7 +43,8 @@ sync() {
     aws s3 sync ${SOURCE_DIR} s3://${BUCKET_NAME}${BUCKET_PATH} --sse \
         --no-guess-mime-type --content-type "${2}" --metadata-directive "REPLACE" \
         --exclude "*" --include "${1}" \
-        --cache-control "max-age=3600"
+        --cache-control "max-age=3600" \
+        --profile ${AWS_DEFAULT_PROFILE}
 }
 
 # /etc/mime.types
@@ -58,4 +57,5 @@ sync "*.html"        "text/html; charset=utf-8"
 # Upload remaining and remove unused
 aws s3 sync ${SOURCE_DIR} s3://${BUCKET_NAME}${BUCKET_PATH} --sse \
     --cache-control "max-age=3600" \
-    --delete
+    --delete \
+    --profile ${AWS_DEFAULT_PROFILE}
